config/routes.rb
Bardbarian::Application.routes.draw do


  resources :characters
  resources :campaigns

  resources :classes
  resources :skills
  resources :feats

  match '/:controller(/:action(/:id))'
end

app/models/ability.rb
class Ability < ActiveRecord::Base

  belongs_to :level
  has_many :tiers

end

app/models/klass.rb
class Klass < ActiveRecord::Base

  has_and_belongs_to_many :skills
  has_many :levels

  scope :base_classes, where(:base_class => 1)
  scope :prestige_classes, where(:base_class => 0)

  def level_bab(lvl)
    return lvl if bab == 2
    bab == 1 ? (lvl*3)/4 : lvl/2
  end

  def level_ref(lvl)
    ref == 1 ? lvl/2 + 2 : lvl/3
  end

  def level_fort(lvl)
    fort == 1 ? lvl/2 + 2 : lvl/3
  end

  def level_will(lvl)
    will == 1 ? lvl/2 + 2 : lvl/3
  end

end

app/models/level.rb
class Level < ActiveRecord::Base

  belongs_to :klass
  has_and_belongs_to_many :abilities

  validates_uniqueness_of :rank, :scope => :klass_id

end

app/models/skills.rb
class Skill < ActiveRecord::Base

  has_and_belongs_to_many :klasses

end

app/models/tier.rb
class Tier < ActiveRecord::Base

  belongs_to :ability

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_active_nav

  def set_active_nav
    @active_nav = params[:controller]
  end


end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def skills
  end

  def feats
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  before_filter do
    @active_nav = "characters"
  end

  def index
  end

end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController

  before_filter :load_klass

  def index
    @base_classes = Klass.base_classes
    @prestige_classes = Klass.prestige_classes
  end

  def show
    @levels = @klass.levels
  end

  def new

  end

  def create

  end

  def edit
    @levels = @klass.levels
  end

  def update
    @klass.update_attributes(params[:klass])
    redirect_to :action => :edit, :id => @klass.id
  end

  def destroy

  end

  def add_level
    @level = Level.new(:rank => @klass.levels.count+1 )
    @klass.levels << @level
  end

  private
  def load_klass
    if params[:id]
      @klass = Klass.find(params[:id])
    end
  end

end

app/controllers/feats_controller.rb
class FeatsController < ApplicationController
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/dm_helper.rb
module DmHelper
end

app/helpers/feats_helper.rb
module FeatsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/characters/index.html.erb
<% content_for :right_sidebar do %>
<h2><%= image_tag "icons/h_donations_for_us.gif"%></h2>
<p><%= image_tag "icons/pic_2.jpg"%></p>
<p>If you're looking for beautiful and professionally made templates you can find them at <a href="http://www.templatebeauty.com">Template Beauty</a>.</p>
<p>Even more websites all about website templates on <a href="http://www.justwebtemplates.com">Just Web Templates</a>.</p>
<p class="more"><a href="#"><%= image_tag "icons/btn_click_here.gif"%></a></p>
<h2><%= image_tag "icons/h_gallery.gif"%></h2>
<div id="gallery">
  <a href="#"><%= image_tag "icons/gal_1.jpg"%></a>
  <a href="#"><%= image_tag "icons/gal_2.jpg"%></a>
  <a href="#"><%= image_tag "icons/gal_3.jpg"%></a>
</div>
<% end %>

<h2><%= image_tag "icons/h_welcome_to_our_site.gif"%></h2>
<p>Don't forgot to check <a href="http://www.freewebsitetemplates.com">free website templates</a> every day, because we add at least one free website template daily.</p>

<p>This is a template designed by free website templates for you for free you can replace all the text by your own
  text. This is just a place holder so you can see how the site would look like.</p>

<p>You can remove any link to our websites from this template you're  free to use the template without linking
  back to us. Don't want your boss to know you used a free website template ;) .</p>

<p>If you're having problems editing the template please don't hesitate to ask for help on the <a href="http://www.freewebsitetemplates.com/forum/">forum</a>.</p>

<p>If you're looking for beautiful and professionally made templates you can find them at <a href="http://www.templatebeauty.com">Template Beauty</a>.</p>
<p>Even more websites all about website templates on <a href="http://www.justwebtemplates.com">Just Web Templates</a>.</p>
<p class="more"><a href="#">more</a></p>
<h2>
  <%= image_tag "icons/h_needs.gif"%></h2>
  <%= image_tag "icons/pic_3.jpg", :class => :left%>
<p><a href="#">Lorem ipsum dolor</a> sit amet, consectetuer adipiscing elit. Mauris ut elit. Sed eu pede. Morbi quis ante a pede feugiat egestas. Etiam feugiat mi in pede. Aenean massa sem.</p>
<ul class="plussbullets">
  <li><a href="#">Lorem ipsum dolor sit amet, consectetuer adipiscing</a></li>
  <li><a href="#">Elit. Mauris ut elit. Sed eu pede. Morbi quis ante a</a></li>
  <li><a href="#">Pede feugiat egestas. Etiam feugiat mi in pede. Aenean massa sem.</a></li>
</ul>

app/views/classes/_level_row.html.erb
<tr id="level_<%=level.rank%>">
  <td> <%= level.rank %> </td>
  <td> +<%= @klass.level_bab(level.rank) %></td>
  <td> +<%= @klass.level_fort(level.rank) %></td>
  <td> +<%= @klass.level_ref(level.rank) %></td>
  <td> +<%= @klass.level_will(level.rank) %></td>
  <td> <%= text_field_tag "level[${level.rank}][specials]" %> </td>
</tr>

app/views/classes/add_level.js.erb
$('table.class_layout').append("<%= escape_javascript(render(:partial => "level_row", :locals => {:level => @level })) %>")

app/views/classes/edit.html.erb
<div style="margin:auto">
<h1> Editing <%= @klass.name %></h1>

<% form_for @klass, :url => class_path(@klass) do %>

  <div class="row">
    <label class="form_label" for="klass_name"> Name: </label>
    <%= text_field :klass, :name %>
  </div>
  <div class="row">
    <label class="form_label" for="klass_alignment_restriction"> Alignment Restriction: </label>
    <%= text_field :klass, :alignment_restriction %>
  </div>
  <div class="row">
    <label class="form_label" for="klass_base_class"> Class Type: </label>
      <div class="dropdown">
        <%= select :klass, :base_class, [["Base Class", 1], ["Prestige Class", 0]],  {}, :class => :selectbox %>
      </div>
      <div class="clear"></div>
  </div>
  <div class="row">
    <label class="form_label" for="klass_hit_dice"> Hit Dice: </label>
    <div class="dropdown">
      <%= select :klass, :hit_dice, [4,6,8,10,12].collect{|c| ["D#{c}", c]},  {}, :class => :selectbox %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="row">
    <label class="form_label" for="klass_skill_ranks"> Skill Ranks: </label>
    <div class="dropdown">
      <%= select :klass, :skill_ranks, [2,4,6,8].collect{|c| ["#{c}+int", c]},  {}, :class => :selectbox %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="row">
    <label class="form_label" for="klass_bab"> BAB: </label>
    <div class="dropdown">
      <%= select :klass, :bab, [["Good", 2], ["Medium", 1], ["Poor", 0]],  {}, :class => :selectbox %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="row">
    <label class="form_label" for="klass_fort"> Fort Save: </label>
    <div class="dropdown">
      <%= select :klass, :fort, [["Good", 1], ["Poor", 0]],  {}, :class => :selectbox %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="row">
    <label class="form_label" for="klass_ref"> Reflex Save: </label>
    <div class="dropdown">
      <%= select :klass, :ref, [["Good", 1], ["Poor", 0]],  {}, :class => :selectbox %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="row">
    <label class="form_label" for="klass_will"> Will Save: </label>
    <div class="dropdown">
      <%= select :klass, :will, [["Good", 1], ["Poor", 0]], {}, :class => :selectbox %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="row">
    <label class="form_label">&nbsp;</label>
    <%= submit_tag "Update" %>
  </div>
<% end %>

  <% if @levels.any? %>
  <table class="class_layout">
    <tr>
      <th> Level </th>
      <th> BAB </th>
      <th> Fort </th>
      <th> Ref </th>
      <th> Will </th>
      <th> Special </th>
    </tr>
    <% @levels.each do |lvl| %>
      <%= render :partial => "level_row", :locals => {:level => lvl} %>
    <% end %>
  </table>
  <div style="width: 90%; text-align:right">
    <%= link_to({:action => :add_level, :id => @klass.id}, :remote => true ) do%>
      <button class="round-all"> Add Level </button>
    <% end %>
  </div>
  <% end %>
</div>

app/views/classes/index.html.erb
<h1> Base Classes </h1>

<ul>
  <% @base_classes.each do |klass| %>
    <li><%= link_to klass.name, edit_class_path(klass) %> </li>
  <% end %>
</ul>

<h1> Prestige Classes </h1>

<ul>
  <% @prestige_classes.each do |klass| %>
    <li><%= klass.name %> </li>
  <% end %>
</ul>

app/views/classes/show.html.erb
<h1> <%= @klass.name $> </h1>

<% form_tag do %>

  <table>
    <tr>
      <th> Level </th>
      <th> Special </th>
    </tr>
    <%= @levels.each do |lvl| %>
    <tr>
      <td> <%= lvl.rank %> </td>
      <td> <%= text_field_tag "level[${lvl.rank}][specials]" %> </td>
    </tr>
    <% end %>

<% end %>

app/views/layouts/_primary_nav.html.erb
<div class="main_logo">
  <div class="header"> <h1><%= image_tag "ui/ddlogo.png"%></h1></div>
</div>
<div class="nav">
  <ul id="nav">
    <li class="round-top nav_campaigns">
      <%= link_to "Campaigns", campaigns_path%>
    </li>
    <li class="round-top nav_characters">
      <%= link_to "Characters", characters_path %>
    </li>
    <li class="round-top nav_classes">
      <%= link_to "Classes", classes_path %>
    </li>
    <li class="round-top nav_skills">
      <%= link_to "Skills", skills_path%>
    </li>
    <li class="round-top nav_feats">
      <%= link_to "Feats", feats_path%>
    </li>

  </ul>
</div>

app/views/layouts/_subnav.html.erb
<div>
  <ul id="nav">
    <% @subnav.each_pair do |name, link| %>
      <li class="round-top subnav_<%=name.downcase.gsub(' ', '_')%>"><%= link_to name, link %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bardbarian</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "jquery.selectbox-0.5" %>
    <%= csrf_meta_tag %>
    <script type="text/javascript">
      $(function(){
        $("li.nav_<%=@active_nav%>").addClass("active");
        $("li.subnav_<%=@active_subnav%>").addClass("active");
        $('.selectbox').selectbox();
        if($.trim($("div.body-right").text()) == ""){
          $("div.body-right").remove();
          $("div.body-left").removeClass("body-left");
        }
      });
    </script>
  </head>
  <body>
    <div class="heading">
      <%= render :partial => "/layouts/primary_nav" %>
    </div>
    <%= render :partial => "layouts/subnav" if @subnav %>

    <div id="content" class="round-all">
        <div style="padding-top:50px" class="body-left">
          <%= yield %>
        </div>

        <div style="padding-top:50px" class="body-right">
          <%= yield(:right_sidebar) %>
        </div>
      <div class="clear"></div>
    </div>
    <div class="footer">
      <p>&copy; 2006 all rights reserved.</p>
    </div>

  </body>
</html>